# -*- coding: utf-8 -*-
"""assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1giz1CLP4N6ESPCX3z6MUh-frH7nMdkmR

### Question 1 (20%)
Load the energy data from the file Energy Indicators.xls, which is a list of indicators of energy supply and renewable electricity production from the United Nations for the year 2013, and should be put into a DataFrame with the variable name of <b>energy</b>.<br><br>

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:<br><br>

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`<br><br>

Convert Energy Supply to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as np.NaN values.<br><br>

Rename the following list of countries (for use in later questions):<br><br>

"Republic of Korea": "South Korea",<br>
"United States of America": "United States",<br>
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",<br>
"China, Hong Kong Special Administrative Region": "Hong Kong"<br><br>

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these,<br>
e.g.<br><br>

'Bolivia (Plurinational State of)' should be 'Bolivia',<br>
'Switzerland17' should be 'Switzerland'.<br><br><br>

Next, load the GDP data from the file world_bank.csv, which is a csv containing countries' GDP from 1960 to 2015 from World Bank. Call this DataFrame <b>GDP</b>.<br><br>

Make sure to skip the header, and rename the following list of countries:<br><br>

"Korea, Rep.": "South Korea", <br>
"Iran, Islamic Rep.": "Iran",<br>
"Hong Kong SAR, China": "Hong Kong"<br><br><br>


Finally, load the Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology from the file scimagojr-3.xlsx, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame <b>ScimEn</b>.<br><br>

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15).<br><br>

The index of this DataFrame should be the name of the country, and the columns should be `['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']`.<br><br>

<i>This function should return a DataFrame with 20 columns and 15 entries.</i>
"""

def answer_one():
    import pandas as pd
    import numpy as np
    
    energy=pd.read_excel('Energy Indicators.xls',header=None)
    energy=energy.drop([0,1],axis=1)
    energy=energy.drop([i for i in range(18)],axis=0)
    energy=energy.drop([i for i in range(245,283)],axis=0)
    energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    energy['Energy Supply']=energy['Energy Supply']*1000000
    #energy['Energy Supply']=energy['Energy Supply'].astype(float)
    energy=energy.replace({'...': np.nan})
    energy=energy.reset_index()
    energy=energy.drop(['index'],axis=1)
    energy['Country'] = energy['Country'].str.replace('\d+', '')
    energy['Country']=energy['Country'].str.replace(r' \(.*\)','')
    energy=energy.set_index('Country')
    energy=energy.rename(index={"Republic of Korea": "South Korea", "United States of America": "United States", "United Kingdom of Great Britain and Northern Ireland": "United Kingdom","China, Hong Kong Special Administrative Region": "Hong Kong"})
    
    GDP=pd.read_csv('world_bank.csv',skiprows=4)
    GDP=GDP.replace(to_replace ='Korea, Rep.', value ='South Korea')
    GDP=GDP.replace(to_replace ='Iran, Islamic Rep.', value ='Iran')
    GDP=GDP.replace(to_replace ='Hong Kong SAR, China', value ='Hong Kong')
    GDP=GDP.loc[:,['Country Name','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015']]
    GDP=GDP.rename(columns={'Country Name': 'Country'})
    GDP=GDP.set_index('Country')
    
    ScimEn=pd.read_excel('scimagojr-3.xlsx',Header=None)
    ScimEn=ScimEn.set_index('Country')
    ScimEn=ScimEn[:15]
    
    tmp=pd.merge(ScimEn,energy,how='inner',left_index=True,right_index=True)
    tmp=pd.merge(tmp,GDP,how='inner',left_index=True,right_index=True)
    
    return tmp